### ISSUE TITLE
Дополнительные сайты для списка PAC-скрипта

### ISSUE THREAD

**Issue by SharkTPO** [An-Eugene/ss_conditions#2]
Вот такие сайты на любой вкус и цвет можно добавить всписок ввиду их региональных ограничений:
`"*.ggpht.com/",
"*.wikidot.com",
"soundcloud.com",
"medium.com",
"claude.ai",
"*.manticgames.com",
"programm.top",
"*.canva.com",
"5e.tools",
"hide.me",
"*.knowyourmeme.com",
"*.x.com",
"*.oculus.com",
"*.meta.com",
"*.tiktok.com",
"*.pixiv.net",
"mintmanga.live",
"nyaa.si",
"hentaichan.live",
"yande.re",
"danbooru.donmai.us",
"konachan.com",
"*.hentai.name",
"nhentai.to",
"nhentai.net",
"*.deviantart.com",
"*.furaffinity.net",
"*.remove.bg",`

**Comment by An-Eugene** [comment]
Благодарю за участие) Вроде, некоторые уже добавлены: забанен yt3.ggpht.com, не обязательно весь домен добавлять. И навскидку пара доменов присутствует уже в списке.

Как будет время - просмотрю кто есть кто и пополню список

**Comment by An-Eugene** [comment]
programm.top - вроде, работает, уточните, пожалуйста
5e.tools - вроде, работает, уточните, пожалуйста
x.com - домен не заблокирован, редиректит на twitter, а сам twitter вместе с CDN внесён уже
oculus.com и meta.com - уточните, там есть какая-то блокировка со стороны сайта? Сам сайт работает, вроде как
tiktok.com - не уверен, есть ли смысл вносить его. Без VPN он работает в урезанном режиме, а для нормальной работы с телефона, вроде как, VPN не помогает, нужна регистрация аккаунта в другой стране (или пропатченный клиент android)
deviantart.com - вроде, работает, уточните, пожалуйста

Остальные домены из списка добавил

**Comment by SharkTPO** [comment]
Добрый день!

- programm.top
- 5e.tools
У меня работают, добавил по отызвам знакомых. 
Возможно, были проблемы с ограничением с доступом стороны сайтов в прошлом. **Предлагаю убрать.**

-  x.com
Добавил по причине "сегодня нет, а завтра добавят" (сейчас редирект, все верно). Можно сейчас убрать, конечно.

-  oculus.com и meta.com
При работе с VR-сетом возникают проблемы (обновление без ВПН затруднительно), но, вероятно, это относится к домену  facebook, так как авторизация аккаунта проходит через него.
Однако, два человека с МТС и Дом.ру говорят, что мета и окулус.ком недоступны вообще. 
![изображение](https://github.com/An-Eugene/ss_conditions/assets/54141744/2ed32f3d-cf71-494f-b2ef-c4a800bb73d0)

-  tiktok.com
Понял, не возражаю.

-  deviantart.com
По отзывам пользователя ростелекома - сам сайт грузится, но не подгружаются изображения. Видимо, файловый сервер - как и аватарки в ютубе. Человек с МТСом подтверждает. 
Единственный хостинг, который я там вижу - .wixmp.com, но его нет в списках. 
![WqWiW1_T-us 1](https://github.com/An-Eugene/ss_conditions/assets/54141744/56bc991d-dfcf-4372-9756-4cb18cd439dc)
Вот такой скрин дают.

Add:
- libgen.is - недоступен на МТС и Дом.ру (у меня доступен). Однако, он может быть недоступен и через VPN для некоторых локаций, так как является сайтом "пиратского распространения научных статей". 
- bard.google.com - ограничения доступа к функции для России.

**Comment by An-Eugene** [comment]
По поводу deviantart: там действительно CDN на домене wixmp.com, однако мной он в список уже был внесён, поэтому я и удивился (можете сверяться со списком в /rules/rules_proxy, список отсортирован в алфавитном порядке **_по домену_**). Вносить сам deviant смысла не вижу, его вряд ли забанят, так как на самом домене не хранится ничего провоцирующего на блокировку.

libgen у меня уже был внесён, оказывается, но другой домен. Добавил со всеми зеркалами.

Остальные тоже добавил. Пусть будут, как минимум, эти домены в группе риска, а как максимум - у кого-то уже забанено (лично проверить не могу, нет ни МТС, ни домру)

**Comment by SharkTPO** [comment]
rentry.co - аналог Telegraph. По каким-то причинам не доступен без впн. Возможно какие-то публикации с помощью этого сервиса кто-то делал.

**Comment by SharkTPO** [comment]
Добрый день!
Предлагаю добавить:
`"*.githubcopilot.com",
"*.copilot.cx",
"*.bing.com",`
Чтобы работали AI-сервисы майкрософт и копилот.

**Comment by An-Eugene** [comment]
Резонно. Добавил

**Comment by SharkTPO** [comment]
Сегодня вскрылась проблема с https://designer.microsoft.com/

**Comment by SharkTPO** [comment]
Предлагаю добавить:
"*.bbc.com",
"*.osti.gov",
Последний, не смотря на смущающий домен - нужен был для чтения научных монографий в области атомной энергетики (звучу как шпион, да).

**Comment by An-Eugene** [comment]
> bbc.com

Уже давно добавлен

> osti.gov

Сейчас добавлю. Вообще .gov, если не ошибаюсь, домен правительства США. Если таких заблокировано очень много - может, есть смысл внести превентивно весь домен .gov? Или osti - скорее заблокированное исключение, чем правило?

**Comment by SharkTPO** [comment]
> Уже давно добавлен

И правда, видимо не всегда срабатывает маршрутизаций. Часто случается, что перестает работать что-то из списка PAC-файла. В браузере не использую других впн-плагинов (Firefox). Чаще перезагружать надо соединение.

> есть смысл внести превентивно весь домен .gov? 

Думаю, что есть смысл. Хотя не все сайты заблокированы.
Это не то чтобы часто посещаемые сайты, потому маршрутизация не будет критичной.

**Comment by An-Eugene** [comment]
> > Уже давно добавлен
> 
> И правда, видимо не всегда срабатывает маршрутизаций. Часто случается, что перестает работать что-то из списка PAC-файла. В браузере не использую других впн-плагинов (Firefox). Чаще перезагружать надо соединение.
> 
> > есть смысл внести превентивно весь домен .gov?
> 
> Думаю, что есть смысл. Хотя не все сайты заблокированы. Это не то чтобы часто посещаемые сайты, потому маршрутизация не будет критичной.

Очень странно. Возможно, причина в неоптимизированном PAC файле, от чего он слишком долго определяет нужный домен. В планах позже обкатать оптимизацию в другой ветке.
Изредка бывает, что что-то сразу не прогружается, но банальный F5 спасает

**Comment by SharkTPO** [comment]
Возможно!
--
Но вот я ещё заметил странный парадокс, который не относится напрямую к PAC-файлу, но к работе приложения SS:
В России недоступен Copilot (Microsoft), который работает в Edge.
Он доступен в Молдове и Финляндии официально (мои VPS там). Но при использовании SS с одним и тем же PAC-файлом или полной маршрутизацией:
- не работает через Финский VPS;
- работает через Молдовский VPS.

Однако: 
- работает через Финский и Молдовский VPS, если подключение осуществлено через Outline. 

В чем причина - не разобрался. Явно в приложении SS. Не в PAC-файле, потому что молдовский сервер его обрабатывает и доступ имеется.
Приходится переключаться между серверами ради доступа, чтобы не дергать Outline.

**Comment by SharkTPO** [comment]
Обнаружил проблему для itch.io - не знаю за что блокируют, но вот.

**Comment by SharkTPO** [comment]
Ещё сайт с пиратскими переводами книг. Искал "Легенду о героях галактики" (романы).
`"coollib.net",`

**Comment by An-Eugene** [comment]
Благодарю, coollib внёс в список
