### ISSUE TITLE
Gemini от гугла

### ISSUE THREAD

**Issue by Koiplan** [An-Eugene/ss_conditions#3]
Привет. Не уверен, что проблема в PAC, но все же: Gemini от гугла не запускается через SS. В аутлайн работат нормально, делаю вывод, что не в VPS проблема. Подскажите, нужно обновить PAC, или руки мне?

**Comment by An-Eugene** [comment]
Всё верно, я не вносил google.com в PAC файл. Только несколько поддоменов, среди которых нет gemini.

Добавил, скоро должно обновиться.

Вообще использовать Outline не обязательно, можно в Shadowsocks включать режим не сценарий настройки (PAC), а "для всей системы", будет работать аналогично
